### ISSUE TITLE
Ignore Scale Node Flag - Incorrect on Export

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SonicAdventureBlenderIO#14] opened 2024-06-24 00:49 UTC
Importing an object that has any nodes set to use the Ignore Scale Node flag will import with that flag set, however exports will set the flag to false. It appears that the flag on export may unintentionally be getting the Ignore Rotation flag instead as that flag being set sets both Ignore Rotation and Ignore Scale on export.

Steps to reproduce are simple, [import the model in this zip](https://github.com/user-attachments/files/15948515/s_kihon10_sonic.nja.zip) and export it back to sa1mdl. Any nodes with the Ignore Scale set to True in Blender will have that flag set to False on export. 

For reference, the head mesh and the palm meshes have only the Ignore Scale flag set to True, and it will be False on export. The eye globe mesh, however, has both Ignore Scale and Ignore Rotation set to True, and this one will export correctly.

**Comment by Justin113D** [comment] 2024-07-27 17:38
This works as intended*. You have to uncheck "Automatic node attribute" on export.

*However, if the scale is (1,1,1), it should still automatically evaluate that as "no scale"... So this is still an issue, just a completely different one

**Comment by Justin113D** [comment] 2024-08-06 16:35
Fixed in release 2.2.0

**Closed by Justin113D** 2024-08-06 16:35 UTC
Labels: bug
